
acquire_data:
  path: data/raw/bmw.csv
  columns: ['model', 'year', 'price', 'transmission',
            'mileage', 'fuelType', 'mpg', 'engineSize']

get_features:
  cat_col: ['model','transmission','fuelType']

split_data:
  ratio: 0.3
  random_state: 22
  target: 'price'

train_model:
  n_estimators: 10
  max_depth: 40
  random_state: 22